export const REACT_APP_EMAILJS_SERVICEID = process.env.REACT_APP_EMAILJS_SERVICEID;
export const REACT_APP_EMAILJS_TEMPLATEID = process.env.REACT_APP_EMAILJS_TEMPLATEID;
export const REACT_APP_EMAILJS_USERID = process.env.REACT_APP_EMAILJS_USERID;
export const REACT_APP_BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
